sudo: true

language: python

before_install:
  - sudo apt-get -qq update

addons:
  apt:
    packages:
    - gcc
    - g++
    - gfortran

env:
  global:
    # Directory where tests are run from
    - TEST_DIR=/tmp/skutil
    - OMP_NUM_THREADS=4
    - OPENBLAS_NUM_THREADS=4
  matrix:
   - DISTRIB="conda" PYTHON_VERSION="2.7" SCIKIT_LEARN_VERSION="0.17.1"
     WITH_MATPLOTLIB="true" WITH_SEABORN="true" COVERAGE="true"
   - DISTRIB="conda" PYTHON_VERSION="2.7" SCIKIT_LEARN_VERSION="0.17.1"
     WITH_MATPLOTLIB="false" WITH_SEABORN="false" COVERAGE="true"
   - DISTRIB="conda" PYTHON_VERSION="2.7" SCIKIT_LEARN_VERSION="0.18"
     WITH_MATPLOTLIB="true" WITH_SEABORN="true" COVERAGE="true"
   - DISTRIB="conda" PYTHON_VERSION="2.7" SCIKIT_LEARN_VERSION="0.18"
     WITH_MATPLOTLIB="false" WITH_SEABORN="false" COVERAGE="true"
#   - DISTRIB="conda" PYTHON_VERSION="3.5" SCIKIT_LEARN_VERSION="0.17.1"
#     WITH_MATPLOTLIB="true" WITH_SEABORN="true" COVERAGE="true"
#   - DISTRIB="conda" PYTHON_VERSION="3.5" SCIKIT_LEARN_VERSION="0.17.1"
#     WITH_MATPLOTLIB="false" WITH_SEABORN="false" COVERAGE="true"
#   - DISTRIB="conda" PYTHON_VERSION="3.5" SCIKIT_LEARN_VERSION="0.18"
#     WITH_MATPLOTLIB="true" WITH_SEABORN="true" COVERAGE="true"
#   - DISTRIB="conda" PYTHON_VERSION="3.5" SCIKIT_LEARN_VERSION="0.18"
#     WITH_MATPLOTLIB="false" WITH_SEABORN="false" COVERAGE="true"

matrix:
  allow_failures:
    - python: 3.5

install: source build_tools/travis/install.sh
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 5 # give xvfb some time to start by sleeping for 5 seconds
script: bash build_tools/travis/test_script.sh
after_success: source build_tools/travis/after_success.sh

