sudo: true
language: python
python:
  - "2.7"
  #- "3.2"
  #- "3.3"
  #- "3.4"
  #- "3.5"

before_install:
  - sudo apt-get -qq update
  - brew update
  - brew install gcc

## Install the packages
install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi

  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda

  # Useful for debugging any issues with conda
  - conda info -a

  # dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy scikit-learn pandas coverage
  - source activate test-environment

  # Coverage packages
  - conda install --yes -c dan_blanchard python-coveralls nose-cov
  - pip install coveralls
  - pip install matplotlib
  - python setup.py install

## Run tests
script: 
  - nosetests --with-coverage --cover-package=skutil --logging-level=INFO

## Compute coverage
after_success:
  - coveralls
