sudo: true
language: python
python:
  - "2.7"
  - "3.5"

env:
 - COMBINATION=sklearn-0-17-matplotlib-seaborn
 - COMBINATION=sklearn-0-17-without-matplotlib-seaborn
 - COMBINATION=sklearn-0-18-matplotlib-seaborn
 - COMBINATION=sklearn-0-18-without-matplotlib-seaborn


## Install the packages
install:
  - chmod 777 ./build_tools/travis/install.sh
  - ./build_tools/travis/install.sh

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 5 # give xvfb some time to start by sleeping for 5 seconds

## Run tests
script:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      nosetests --with-coverage --cover-package=skutil --logging-level=INFO;
    else
      nosetests --logging-level=INFO;
    fi

# Compute Coverage Using Coveralls
after_success:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      coveralls;
    fi

