sudo: true
language: python
python:
  - "2.7"

before_install:
  - sudo apt-get -qq update

addons:
  apt:
    packages:
    - gcc
    - g++
    - gfortran

env:
 - TOX_ENV=python-2-7-sklearn-0-17
 - TOX_ENV=python-2-7-sklearn-0-18
 # - TOX_ENV=python-3-5-sklearn-0-17
 # - TOX_ENV=python-3-5-sklearn-0-18

## Install the packages
install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi

  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda

  # Useful for debugging any issues with conda
  - conda info -a

  # dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy pandas coverage cython
  - source activate test-environment

  # Coverage packages
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      conda install --yes -c dan_blanchard python-coveralls nose-cov;
    fi

  - pip install coveralls
  - pip install matplotlib
  - pip install seaborn
  #- pip install tox
  - if [[ "$TOX_ENV" == "python-2-7-sklearn-0-17"]]; then
       pip install scikit-learn==0.17.1
    else
       pip install scikit-learn==0.18
    if
  - pip install http://h2o-release.s3.amazonaws.com/h2o/rel-turchin/9/Python/h2o-3.8.2.9-py2.py3-none-any.whl
  - python setup.py develop

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 5 # give xvfb some time to start by sleeping for 5 seconds

## Run tests
script:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      nosetests --with-coverage --cover-package=skutil --logging-level=INFO;
    else
      nosetests --logging-level=INFO;
    fi

# Compute Coverage Using Coveralls
after_success:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      coveralls;
    fi