sudo: true
language: python
python:
  - "2.7"

before_install:
  - sudo apt-get -qq update

addons:
  apt:
    packages:
    - gcc
    - g++
    - gfortran

env:
 - TOX_ENV=python-2-7-sklearn-0-17
 - TOX_ENV=python-2-7-sklearn-0-18

## Install the packages
install:
- pip install tox

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 5 # give xvfb some time to start by sleeping for 5 seconds

script:
  - tox -e $TOX_ENV #set scikit-learn and python version dynamically

# Compute Coverage Using Coveralls
after_success:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      coveralls;
    fi
