sudo: true
language: python
python:
  - "2.7"
  - "3.5"

env:
 - COMBINATION=sklearn-0-17-matplotlib-seaborn
 - COMBINATION=sklearn-0-17-without-matplotlib-seaborn
 - COMBINATION=sklearn-0-18-matplotlib-seaborn
 - COMBINATION=sklearn-0-18-without-matplotlib-seaborn


## Install the packages
install:
  - chmod 777 ./build_tools/travis/install.sh
  - ./build_tools/travis/install.sh

script:
  - echo -e "\nUNIT TESTS SUCCESSFULLY COMPLETED!"